CREATE TABLE IF NOT EXISTS users (
    user_id TEXT PRIMARY KEY UNIQUE NOT NULL,
    username TEXT NOT NULL,
    team_name TEXT,
    FOREIGN KEY (team_name) REFERENCES teams(team_name) ON DELETE RESTRICT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)

CREATE INDEX IF NOT EXISTS idx_team_name ON users (team_name);
CREATE INDEX IF NOT EXISTS idx_is_active ON users (is_active);

CREATE TABLE IF NOT EXISTS teams (
    team_name TEXT PRIMARY KEY UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
